# Objective: Prepare a Clean and Targeted Customer Call List

### Importing necessary libraries for data manipulation and analysis

In [201]:
import pandas as pd
import numpy as np
import re

### Reading data from an Excel file into a pandas DataFrame

In [202]:
df=pd.read_excel(r'C:\Users\abhay\Desktop\portfolio\pandas data cleaning\Customer Call List.xlsx')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

### Total columns from the df

In [203]:
df.columns

Index(['CustomerID', 'First_Name', 'Last_Name', 'Phone_Number', 'Address',
       'Paying Customer', 'Do_Not_Contact', 'Not_Useful_Column'],
      dtype='object')

### Basic info about df

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         21 non-null     int64
 1   First_Name         21 non-null     object
 2   Last_Name          20 non-null     object
 3   Phone_Number       19 non-null     object
 4   Address            21 non-null     object
 5   Paying Customer    21 non-null     object
 6   Do_Not_Contact     17 non-null     object
 7   Not_Useful_Column  21 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

### Removing duplicate rows from the DataFrame

In [205]:
df=df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

### Dropping the specified column ('Not_Useful_Column') from the DataFrame

In [206]:
df=df.drop(columns='Not_Useful_Column')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

### Applying a lambda function to clean 'Last_Name' column by removing non-alphabetic characters

In [207]:
df['Last_Name']=df['Last_Name'].apply(lambda x: re.sub(r'[^A-Za-z]+','',str(x)) if pd.notna(x) else '')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

## Cleaning 'Phone_Number' column:
### - Removing non-numeric characters using a lambda function
### - Formatting the phone numbers by adding dashes between segments
### - Replacing double dashes with a single dash in the entire column

In [208]:
df['Phone_Number']=df['Phone_Number'].apply(lambda x: re.sub(r'[^0-9]+','', str(x)) if pd.notna(x) else '').apply(lambda x: '-'.join([x[:3],x[3:7],x[7:]]) if pd.notna(x) else '')
df['Phone_Number']=df['Phone_Number'].str.replace('--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-5455-421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-6439-775,93 West Main Street,No,Yes
2,1003,Walter,White,706-6950-392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-5432-345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-6783-469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-7622-467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-6783-469,98 Clue Drive,N,No
8,1009,Gandalf,,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-5455-421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-6950-392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-5432-345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-6783-469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-7622-467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-5455-421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-6439-775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-6950-392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-6783-469,"910 Tatooine Road, Tatooine",Yes,N

### Splitting 'Address' column into separate columns for 'street', 'state', and 'zip'

In [209]:
df[['street','state','zip']]=df['Address'].str.split(',',expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-6439-775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-6950-392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-5432-345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-6783-469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-7622-467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-6783-469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-5455-421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-6950-392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-5432-345,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-6783-469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-7622-467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-5455-421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-6439-775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-6950-392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-6783-469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

## Cleaning 'Paying Customer' column:
### - Replacing 'Yes' with 'Y' and 'No' with 'N'
### - Replacing 'N/a' with an empty string

In [210]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y').str.replace('No','N')
df['Paying Customer']=df['Paying Customer'].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-6439-775,93 West Main Street,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,706-6950-392,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-5432-345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-6783-469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-7622-467,768 City Parkway,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-6783-469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-5455-421,"25th Main Street, New York",Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-6950-392,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-5432-345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-6783-469,343 City Parkway,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-7622-467,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-5455-421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-6439-775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-6950-392,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-6783-469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

## Cleaning 'Do_Not_Contact' column:
### - Replacing 'No' with 'N' and 'Yes' with 'Y'
### - Filling NaN values with an empty string

In [211]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N').str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-6439-775,93 West Main Street,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-6950-392,298 Drugs Driveway,N,,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-5432-345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-6783-469,123 Dragons Road,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-7622-467,768 City Parkway,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-6783-469,98 Clue Drive,N,N,98 Clue Drive,None,None
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,123-5455-421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-6950-392,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-5432-345,2039 Main Street,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-6783-469,343 City Parkway,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-7622-467,214 HR Avenue,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-5455-421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-6439-775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-6950-392,3498 Super Lane,Y,,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-6783-469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

### Dropping the 'Address' column from the DataFrame

In [212]:
df=df.drop('Address', axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-6439-775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-6950-392,N,,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-5432-345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-6783-469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-7622-467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-6783-469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,,,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,123-5455-421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-6950-392,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-5432-345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-6783-469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-7622-467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-5455-421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-6439-775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-6950-392,Y,,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-6783-469,Y,N,910 Tatooine Road,Tatooine,None

## Cleaning 'street' column:
### - Replacing 'N/a' with an empty string

In [213]:
df['street']=df['street'].str.replace('N/a','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-6439-775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,706-6950-392,N,,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-5432-345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-6783-469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-7622-467,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-6783-469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,,,Y,,123 Middle Earth,None,None
9,1010,Peter,Parker,123-5455-421,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,706-6950-392,Y,,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-5432-345,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-6783-469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-7622-467,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-5455-421,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-6439-775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,706-6950-392,Y,,3498 Super Lane,None,None
18,1019,Creed,Braton,,,Y,,None,None
19,1020,Anakin,Skywalker,876-6783-469,Y,N,910 Tatooine Road,Tatooine,None

## Handling missing values in 'state' and 'zip' columns:
### - Filling NaN values in 'state' and 'zip' columns with an empty string

In [214]:
df['state']=df['state'].fillna('')
df['zip']=df['zip'].fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-6439-775,N,Y,93 West Main Street,,
2,1003,Walter,White,706-6950-392,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-5432-345,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-6783-469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-7622-467,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-6783-469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-5455-421,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,706-6950-392,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-5432-345,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-6783-469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-7622-467,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-5455-421,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-6439-775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,706-6950-392,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,Y,,,
19,1020,Anakin,Skywalker,876-6783-469,Y,N,910 Tatooine Road,Tatooine,

## Filtering DataFrame Rows and Resetting Index
### - Keeping rows where 'Do_Not_Contact' is not 'Y' and 'Phone_Number' is not empty
### - Resetting the index of the DataFrame

In [215]:
df=df.query("Do_Not_Contact!='Y' & Phone_Number!=''")
df=df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,Y,N,123 Shire Lane,Shire,
1,1003,Walter,White,706-6950-392,N,,298 Drugs Driveway,,
2,1005,Jon,Snow,876-6783-469,Y,N,123 Dragons Road,,
3,1008,Sherlock,Holmes,876-6783-469,N,N,98 Clue Drive,,
4,1010,Peter,Parker,123-5455-421,Y,N,25th Main Street,New York,
5,1012,Harry,Potter,706-6950-392,Y,,2394 Hogwarts Avenue,,
6,1013,Don,Draper,123-5432-345,Y,N,2039 Main Street,,
7,1014,Leslie,Knope,876-6783-469,Y,N,343 City Parkway,,
8,1015,Toby,Flenderson,304-7622-467,N,N,214 HR Avenue,,
9,1016,Ron,Weasley,123-5455-421,N,N,2395 Hogwarts Avenue,,
10,1017,Michael,Scott,123-6439-775,Y,N,121 Paper Avenue,Pennsylvania,
11,1018,Clark,Kent,706-6950-392,Y,,3498 Super Lane,,
12,1020,Anakin,Skywalker,876-6783-469,Y,N,910 Tatooine Road,Tatooine,

## Cleaning 'Do_Not_Contact' column:
### - Stripping leading and trailing whitespaces
### - Replacing empty strings with 'N'

In [216]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.strip().replace('','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,street,state,zip
0,1001,Frodo,Baggins,123-5455-421,Y,N,123 Shire Lane,Shire,
1,1003,Walter,White,706-6950-392,N,N,298 Drugs Driveway,,
2,1005,Jon,Snow,876-6783-469,Y,N,123 Dragons Road,,
3,1008,Sherlock,Holmes,876-6783-469,N,N,98 Clue Drive,,
4,1010,Peter,Parker,123-5455-421,Y,N,25th Main Street,New York,
5,1012,Harry,Potter,706-6950-392,Y,N,2394 Hogwarts Avenue,,
6,1013,Don,Draper,123-5432-345,Y,N,2039 Main Street,,
7,1014,Leslie,Knope,876-6783-469,Y,N,343 City Parkway,,
8,1015,Toby,Flenderson,304-7622-467,N,N,214 HR Avenue,,
9,1016,Ron,Weasley,123-5455-421,N,N,2395 Hogwarts Avenue,,
10,1017,Michael,Scott,123-6439-775,Y,N,121 Paper Avenue,Pennsylvania,
11,1018,Clark,Kent,706-6950-392,Y,N,3498 Super Lane,,
12,1020,Anakin,Skywalker,876-6783-469,Y,N,910 Tatooine Road,Tatooine,